spring.application.name=04-ecommerce-api

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080

# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Where uploaded images are stored on disk
#app.upload.dir=C:\Users\user\Desktop\springboot-projects\04-ecommerce-api\imageDirectory
#  uploads/products

app.upload.dir=C:/Users/user/Desktop/springboot-projects/04-ecommerce-api/imageDirectory
